# Generated by Django 5.1 on 2024-08-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(editable=False, max_length=12, null=True, unique=True)),
                ('breed', models.CharField(blank=True, max_length=30, null=True)),
                ('age_in_years', models.FloatField()),
                ('colour', models.CharField(blank=True, max_length=30, null=True)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('other', 'Other')], max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=30)),
                ('weight_in_kgs', models.FloatField()),
                ('distinctive_features', models.CharField(blank=True, max_length=50, null=True)),
                ('micro_chipped', models.BooleanField(default=False)),
                ('animal_photo', models.FileField(default=True, upload_to='images/')),
                ('cage_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.IntegerField(choices=[(0, 'Bird'), (1, 'Cat'), (2, 'Dog'), (3, 'Other')])),
                ('intake_condition', models.IntegerField(choices=[(0, 'Injured'), (1, 'Normal'), (2, 'Other'), (3, 'Sick')])),
                ('intake_type', models.IntegerField(choices=[(0, 'Euthanasia Request'), (1, 'Owner Surrender'), (2, 'Public Assist'), (3, 'Stray'), (4, 'Wildlife')])),
                ('sex_upon_intake', models.IntegerField(choices=[(0, 'Intact Female'), (1, 'Intact Male'), (2, 'Neutered Male'), (3, 'Spayed Female'), (4, 'Unknown')])),
                ('age_upon_intake_years', models.FloatField()),
                ('intake_month', models.IntegerField()),
                ('intake_weekday', models.IntegerField(choices=[(0, 'Friday'), (1, 'Monday'), (2, 'Saturday'), (3, 'Sunday'), (4, 'Thursday'), (5, 'Tuesday'), (6, 'Wednesday')])),
                ('intake_hour', models.IntegerField()),
                ('time_in_shelter_days', models.FloatField()),
                ('is_mix', models.BooleanField()),
                ('animal_has_multicolor_fur', models.BooleanField()),
                ('time_of_day_of_intake', models.IntegerField(choices=[(0, 'Afternoon'), (1, 'Early morning'), (2, 'Evening'), (3, 'Late morning'), (4, 'Night-time')])),
                ('outcome_type', models.IntegerField(choices=[(0, 'Adoption'), (1, 'Euthanasia'), (2, 'Other'), (3, 'Return to Owner'), (4, 'Transfer')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShelterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('name', models.CharField(default=False, max_length=50)),
                ('usertype', models.CharField(choices=[('admin', 'Admin'), ('shelterstaff', 'Shelter-Staff'), ('adopter_or_foster', 'Adopter-or-foster-parent')], default='shelterstaff', max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('new_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=30)),
                ('current_medications', models.CharField(blank=True, max_length=30, null=True)),
                ('known_medical_conditions', models.CharField(blank=True, max_length=30, null=True)),
                ('vaccination_status', models.CharField(choices=[('upto_date', 'Up-to-date'), ('incomplete', 'Incomplete'), ('unknown', 'Unknown')], max_length=30)),
                ('parasite_control', models.CharField(choices=[('flea_tick_prevention', 'Flea-tick-prevention'), ('Deworming', 'deworming')], max_length=30)),
                ('allergies', models.CharField(blank=True, max_length=50, null=True)),
                ('temperament', models.CharField(choices=[('friendly', 'Friendly'), ('shy', 'Shy'), ('aggressive', 'Aggressive')], max_length=30)),
                ('any_aggresive_incidents', models.BooleanField(default=False)),
                ('is_neutered', models.BooleanField(default=False)),
                ('other_observations', models.TextField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to='core.animalonboarding')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousOwnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_owner_known', models.BooleanField(default=True)),
                ('name_of_previous_owner', models.CharField(blank=True, max_length=50, null=True)),
                ('reason_for_intake', models.CharField(choices=[('abandoned', 'Abandoned'), ('owners_moving_away', 'Owner-moving-away'), ('hypoallergens', 'Hypoallergens'), ('unable_to_care_for', 'Unable-to-care-for')], max_length=50)),
                ('los_with_owners_in_years', models.FloatField()),
                ('previous_veterinary_clinic', models.TextField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_owner_info', to='core.animalonboarding')),
            ],
        ),
        migrations.CreateModel(
            name='ShelterAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage_id', models.CharField(max_length=20)),
                ('recommended_next_steps', models.CharField(choices=[('medical_evaluation', 'Medical-evaluation'), ('behaviour_analysis', 'Behaviour-analysis')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_assessments', to='core.animalonboarding')),
            ],
        ),
        migrations.CreateModel(
            name='PotentialAdopterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_foster', models.BooleanField(default=False)),
                ('address', models.TextField(max_length=100)),
                ('first_time_owner', models.BooleanField(default=True)),
                ('have_other_pets', models.BooleanField(default=False)),
                ('preferred_species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('other', 'Other')], default='dog')),
                ('is_a_family', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shelteruser')),
            ],
        ),
        migrations.CreateModel(
            name='HomeInspectionPreAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_eligible_to_adopt', models.BooleanField(default=True)),
                ('other_remarks', models.TextField(max_length=100, null=True)),
                ('sign_of_inspector', models.FileField(upload_to='inspector_sign/')),
                ('sign_of_applicant', models.FileField(upload_to='applicant_sign/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_of_applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.potentialadopterinfo')),
                ('name_of_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shelteruser')),
            ],
        ),
        migrations.CreateModel(
            name='ChatWithGuidelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=250)),
                ('response', models.TextField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shelteruser')),
            ],
        ),
        migrations.AddField(
            model_name='animalonboarding',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_animals', to='core.shelteruser'),
        ),
    ]
