# Generated by Django 5.0.4 on 2024-04-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelteruser',
            options={'ordering': ['created_at']},
        ),
    ]
