# Generated by Django 5.1 on 2024-08-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_animalonboarding_animal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelteruser',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('shelterstaff', 'Shelter_staff'), ('adopter_or_foster', 'Adopter_or_foster_parent'), ('volunteer', 'Volunteer')], default='shelterstaff', max_length=30),
        ),
        migrations.CreateModel(
            name='VolunteerSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_volunteer', models.CharField(max_length=50)),
                ('found_animal_at_location', models.CharField(max_length=100)),
                ('distinctive_features', models.CharField(blank=True, max_length=50, null=True)),
                ('likely_abandoned', models.BooleanField(default=True)),
                ('is_rabid', models.BooleanField(default=False)),
                ('attention_needed', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='Medium')),
                ('is_visibly_injured', models.BooleanField(default=False)),
                ('nametag_found', models.BooleanField(default=False)),
                ('additional_comments', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lost_animal', models.ForeignKey(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('other', 'Other')], default='Dog', on_delete=django.db.models.deletion.CASCADE, to='core.animalonboarding')),
                ('lost_animal_health', models.ForeignKey(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('serious', 'Serious')], default='Healthy', on_delete=django.db.models.deletion.CASCADE, to='core.animalhealth')),
            ],
        ),
    ]
