# Generated by Django 5.0.4 on 2024-04-07 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_animalonboarding_animalhealth_previousownerinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelteruser',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('shelterstaff', 'Shelter-Staff'), ('adopter_or_foster', 'Adopter-or-foster-parent')], default='shelterstaff', max_length=30),
        ),
        migrations.CreateModel(
            name='PotentialAdopterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_foster', models.BooleanField(default=False)),
                ('address', models.TextField(max_length=100)),
                ('first_time_owner', models.BooleanField(default=True)),
                ('have_other_pets', models.BooleanField(default=False)),
                ('preferred_species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('other', 'Other')], default='dog')),
                ('is_family', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shelteruser')),
            ],
        ),
    ]
