# Generated by Django 5.1 on 2024-08-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shelteruser_usertype_volunteersearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteersearch',
            old_name='lost_animal_health',
            new_name='animal_health',
        ),
        migrations.RenameField(
            model_name='volunteersearch',
            old_name='lost_animal',
            new_name='animal_onboarding',
        ),
    ]
