# Generated by Django 5.0.4 on 2024-04-09 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shelteruser_usertype_potentialadopterinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potentialadopterinfo',
            old_name='is_family',
            new_name='is_a_family',
        ),
        migrations.RemoveField(
            model_name='animalonboarding',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='animalonboarding',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='HomeInspectionPreAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_eligible_to_adopt', models.BooleanField(default=True)),
                ('other_remarks', models.TextField(max_length=100, null=True)),
                ('name_of_applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.potentialadopterinfo')),
                ('name_of_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shelteruser')),
            ],
        ),
    ]
