# Generated by Django 5.1.4 on 2024-12-21 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_volunteersearch_is_rabid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalonboarding',
            name='registered_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_animals', to='core.shelteruser'),
        ),
        migrations.AlterField(
            model_name='shelteruser',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shelteruser',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
