# Generated by Django 5.1.4 on 2024-12-21 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_animalonboarding_registered_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='animalonboarding',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_animals', to='core.shelteruser'),
        ),
    ]
