# Generated by Django 5.1.4 on 2024-12-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_animaldocuments_alter_animalonboarding_registered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalonboarding',
            name='animal_photo',
        ),
        migrations.AddField(
            model_name='animaldocuments',
            name='animal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.animalonboarding'),
        ),
        migrations.AddField(
            model_name='animaldocuments',
            name='animal_photo',
            field=models.FileField(default=True, null=True, upload_to='animal_image/'),
        ),
        migrations.AddField(
            model_name='animaldocuments',
            name='other_documents',
            field=models.FileField(default=True, null=True, upload_to='animal_documents/'),
        ),
    ]
