# Generated by Django 5.1.4 on 2024-12-21 17:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_animalonboarding_cage_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalhealth',
            old_name='health_status',
            new_name='intake_condition',
        ),
        migrations.RemoveField(
            model_name='animalhealth',
            name='is_injured',
        ),
        migrations.RemoveField(
            model_name='animalhealth',
            name='is_neutered',
        ),
        migrations.RemoveField(
            model_name='outcomeprediction',
            name='age_upon_intake_years',
        ),
        migrations.RemoveField(
            model_name='outcomeprediction',
            name='animal_has_multicolor_fur',
        ),
        migrations.RemoveField(
            model_name='outcomeprediction',
            name='animal_type',
        ),
        migrations.RemoveField(
            model_name='outcomeprediction',
            name='intake_condition',
        ),
        migrations.RemoveField(
            model_name='outcomeprediction',
            name='intake_hour',
        ),
        migrations.RemoveField(
            model_name='outcomeprediction',
            name='intake_month',
        ),
        migrations.RemoveField(
            model_name='outcomeprediction',
            name='intake_type',
        ),
        migrations.RemoveField(
            model_name='outcomeprediction',
            name='intake_weekday',
        ),
        migrations.RemoveField(
            model_name='outcomeprediction',
            name='is_mix',
        ),
        migrations.RemoveField(
            model_name='outcomeprediction',
            name='sex_upon_intake',
        ),
        migrations.RemoveField(
            model_name='outcomeprediction',
            name='time_in_shelter_days',
        ),
        migrations.RemoveField(
            model_name='outcomeprediction',
            name='time_of_day_of_intake',
        ),
        migrations.RemoveField(
            model_name='shelterassessment',
            name='cage_id',
        ),
        migrations.AddField(
            model_name='animalhealth',
            name='neutering_status',
            field=models.CharField(choices=[('intact', 'Intact'), ('neutered', 'Neutered'), ('unknown', 'Unkwown')], default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='animalonboarding',
            name='is_mix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animalonboarding',
            name='month_of_intake',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='outcomeprediction',
            name='animal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.animalonboarding'),
        ),
        migrations.AddField(
            model_name='shelterassessment',
            name='additional_comments',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='parasite_control',
            field=models.CharField(choices=[('flea_tick_prevention', 'Flea_tick_prevention'), ('deworming', 'Deworming'), ('not_required', 'Not_required')], default='not_required', max_length=30),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='temperament',
            field=models.CharField(choices=[('friendly', 'Friendly'), ('shy', 'Shy'), ('aggressive', 'Aggressive'), ('neutral', 'Neutral')], default='neutral', max_length=30),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='vaccination_status',
            field=models.CharField(choices=[('up_to_date', 'Up_to_date'), ('incomplete', 'Incomplete'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='animalonboarding',
            name='age_in_years',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='animalonboarding',
            name='weight_in_kgs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='previousownerinfo',
            name='los_with_owners_in_years',
            field=models.FloatField(default=2.1),
        ),
        migrations.AlterField(
            model_name='previousownerinfo',
            name='previous_owner_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shelterassessment',
            name='recommended_next_steps',
            field=models.CharField(choices=[('medical_evaluation', 'Medical_evaluation'), ('behaviour_analysis', 'Behaviour_analysis')], max_length=100),
        ),
    ]
