# Generated by Django 5.1.4 on 2024-12-21 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_health_status_animalhealth_intake_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_animal_at_location', models.CharField(max_length=100)),
                ('distinctive_features', models.CharField(blank=True, max_length=50, null=True)),
                ('likely_abandoned', models.BooleanField(default=True)),
                ('attention_needed', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate')),
                ('nametag_found', models.BooleanField(default=False)),
                ('additional_comments', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarness', to='core.animalhealth')),
                ('animal_onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animalonboarding')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shelteruser')),
            ],
        ),
        migrations.DeleteModel(
            name='VolunteerSearch',
        ),
    ]
