# Generated by Django 5.1.4 on 2024-12-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_awarenesscreation_delete_volunteersearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalonboarding',
            name='intake_type',
            field=models.CharField(choices=[('stray', 'Stray'), ('owner_surrender', 'Owner_surrender'), ('public_assist', 'Public_assist'), ('wildlife', 'Wildlife'), ('euthanasia_request', 'Euthanasia_request')], default='stray', max_length=50),
        ),
    ]
