# Generated by Django 5.1.4 on 2024-12-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_animalonboarding_intake_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalhealth',
            name='current_medications',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='intake_condition',
            field=models.CharField(choices=[('normal', 'Normal'), ('injured', 'Injured'), ('aged', 'Aged'), ('sick', 'Sick'), ('feral', 'Feral'), ('pregnant', 'Pregnant'), ('nursing', 'Nursing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='known_medical_conditions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='neutering_status',
            field=models.CharField(choices=[('intact', 'Intact'), ('neutered', 'Neutered'), ('unknown', 'Unkwown')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='parasite_control',
            field=models.CharField(choices=[('flea_tick_prevention', 'Flea_tick_prevention'), ('deworming', 'Deworming'), ('not_required', 'Not_required')], default='not_required', max_length=50),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='temperament',
            field=models.CharField(choices=[('friendly', 'Friendly'), ('shy', 'Shy'), ('aggressive', 'Aggressive'), ('neutral', 'Neutral')], default='neutral', max_length=50),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='vaccination_status',
            field=models.CharField(choices=[('up_to_date', 'Up_to_date'), ('incomplete', 'Incomplete'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='animalonboarding',
            name='breed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animalonboarding',
            name='colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animalonboarding',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=50),
        ),
        migrations.AlterField(
            model_name='animalonboarding',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shelteruser',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shelteruser',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('shelterstaff', 'Shelter_staff'), ('adopter_or_foster', 'Adopter_or_foster_parent'), ('volunteer', 'Volunteer')], default='shelterstaff', max_length=50),
        ),
    ]
