# Generated by Django 5.1.4 on 2024-12-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_animalhealth_current_medications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalonboarding',
            name='breed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
