# Generated by Django 5.1.4 on 2024-12-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_shelteruser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelteruser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
